### ISSUE TITLE
Отсутствует файл `activate_this.py`

### ISSUE THREAD

**Issue by pavel-k-python** [aayartsev/odpm-old#3]
Отсутствует файл `activate_this.py` используемый в [odpm.py#L192](https://github.com/aayartsev/odpm/blob/99fc3db3fe6dc48f4e8a54698336ae03fe007211/odpm/odpm.py#L192)

**Comment by aayartsev** [comment]
Данный файл появляется только когда создано виртуальное окружение. Создается каталог odpm.py#L77 в котором создаются виртуальные окружения для каждой версии odoo. Если он не создался по каким либо причинам, то и не будет этого файла. А так он всегда должен быть в своем виртуальном окружении.
